services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mdb-postgres
    environment:
      POSTGRES_DB: mdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mdb-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mdb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mdb-network

  # Elasticsearch Search Engine
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: mdb-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mdb-network

  # Backend Spring Boot Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mdb-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URIS=http://elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET:-please-change-this-super-secret-jwt-key-in-production-environment-minimum-32-chars}
      - JWT_EXPIRATION=86400000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-your-github-client-id}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-your-github-client-secret}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4200}
      - DDL_AUTO=${DDL_AUTO:-update}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200,http://localhost:3000}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
    restart: on-failure
    networks:
      - mdb-network

  # Frontend Angular Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mdb-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mdb-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  mdb-network:
    driver: bridge